### ISSUE TITLE
[BUG] PowerVS Inages are not loading

### ISSUE THREAD

**Issue by narendermann** [IBM/CRAIG#13]
**Do not include sensitive variables.**

**Describe the bug**
While I try to add a new powervs workspace, its not letting me to do so as it is not loading the images. 

**To Reproduce**
1. Go to 'Power VS Workspace'
2. Click on 'Add Resource'
3. Add the information like WS Name, Zone, Resource Group and here Images are not loadiing

**Expected behavior**
Images should load so that we can select the image to create a WS. Or, make the Image field as optional.

**Logs**
If applicable, add logs to help explain your problem. Include logs as text or as part of a code block. 

**Screenshots**
![image](https://github.com/IBM/CRAIG/assets/54568962/fc7d114f-0ffd-4e95-a515-2be496261550)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Mozilla Firefox ]
 - Version [125.0.1 (64-bit)]

**Comment by jvallexm** [comment]
@narendermann A few questions:
- Are you using a local version of CRAIG? If not, where is the CRAIG deployment hosted?
- Is your IBM Cloud Platform API key added as part of the environment variables?
- Are the resource group and availability zone listed the same as in your cloud account?

This looks to me like something is not set up correctly, I was not able to recreate this issue. Please provide more information

**Comment by jvallexm** [comment]
@narendermann What version of CRAIG are you using?

**Comment by narendermann** [comment]
@jvallexm - here are the answers:

    Are you using a local version of CRAIG? If not, where is the CRAIG deployment hosted? - hosted on code engine
    Is your IBM Cloud Platform API key added as part of the environment variables? - yes
    Are the resource group and availability zone listed the same as in your cloud account? - I am creating the RG and zone is listed as required
What version of CRAIG are you using? - using v1.11.1

**Comment by jvallexm** [comment]
@narendermann I would try updating to the latest version, I believe the Power VS API endpoint changed a few weeks ago and we had to update the back-end calls that retrieve images

**Comment by jvallexm** [comment]
If that does not work, please schedule a meeting with me jennifer.valle@ibm.con and I'll see if we can debug the problem

**Comment by narendermann** [comment]
I am trying to create the new environment and I am getting this now @jvallexm 

nsingh@cloudshell:~$ ./deploy.sh -a "MY API Key" -r ca-tor -g RG-NarenderSingh -e .env -p ce-proj-nsingh -n ghs-icr-nsingh -x ghs-iac -o ca.icr.io -i image-iac-ghs -t latest -s 'https://github.com/IBM/CRAIG' -c main
No ICR namespace found creating one...
Adding namespace 'ghs-icr-nsingh' in resource group 'RG-NarenderSingh' for account GlassHouse Systems in registry ca.icr.io...

Successfully added namespace 'ghs-icr-nsingh'

OK
Selecting project 'ce-proj-nsingh'...
Added context for 'ce-proj-nsingh' to the current kubeconfig file.
OK
Getting image registry access secret 'ibm-cr'...
Updating image registry access secret 'ibm-cr'...
OK
Creating generic secret 'ghs-iac-apikey'...
OK
Creating configmap 'ghs-iac-accountid'...
OK
Run 'ibmcloud ce configmap get -n ghs-iac-accountid' to see more details.
Creating configmap 'ghs-iac-env'...
OK
Run 'ibmcloud ce configmap get -n ghs-iac-env' to see more details.
Creating build 'imgbld-ghs-iac'...
OK
Building the CRAIG container in IBM Code Engine
Getting build 'imgbld-ghs-iac'
Submitting build run 'imgbld-ghs-iac-run-240430-170641611'...
For troubleshooting information visit: https://cloud.ibm.com/docs/codeengine?topic=codeengine-troubleshoot-build.
Run 'ibmcloud ce buildrun get -n imgbld-ghs-iac-run-240430-170641611' to check the build run status.
Run 'ibmcloud ce buildrun logs -f -n imgbld-ghs-iac-run-240430-170641611' to follow the logs of the build run.
Creating image 'ca.icr.io/ghs-icr-nsingh/image-iac-ghs:latest'...
FAILED
json: cannot unmarshal string into Go struct field BuildRunSpec.spec.serviceAccount of type v1alpha1.ServiceAccount

Trace ID: codeengine-cli-fet26vj26u
2024:04:30.17:06:45 FATAL: An error occurred with the image build
