### ISSUE TITLE
[1.8][BUG] Module invalidNumberCheck is exported in disable-save.js but it is not defined there 

### ISSUE THREAD

**Issue by ghost** [IBM/CRAIG#7]
**Do not include sensitive variables.**

**Describe the bug**
In source file disable-save.js the module.exports lists function invalidNumberCheck, but this module is not defined in that file and application does not start.

It seems that the module invalidNumberCheck is defined in icd.js and it is only referenced in the same module.

**Comment by jvallexm** [comment]
this will be fixed in the next push to public
