### ISSUE TITLE
[<1.8>][BUG] script for deploying to IBM Cloud Code Engine is hard-coded for us container registry

### ISSUE THREAD

**Issue by ghost** [IBM/CRAIG#8]
script deploy.sh is hardcoded to use us.icr.io
In essence, craig can't be deployed to any code engine outside of us. It is not acceptable for companies residing in EU

In order to have a more generic usage I have updated the script to accept one additional argument and be able to control which CR is used.
Please see attached new deploy.sh
[deploy.sh.zip](https://github.com/IBM/CRAIG/files/13885862/deploy.sh.zip)

**Comment by jvallexm** [comment]
we are working on a new deploy script that should be out soon, we will take this into consideration as we move forward

**Comment by jvallexm** [comment]
@DougAtIBM A new deployment script is available with the ability to choose the ICR region
